apiVersion: v1
kind: Secret
metadata:
  name: argocd-application-controller-token
  annotations:
    kubernetes.io/service-account.name: argocd-application-controller
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-dex-server-token
  annotations:
    kubernetes.io/service-account.name: argocd-dex-server
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-server-token
  annotations:
    kubernetes.io/service-account.name: argocd-server
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
  name: argocd-secret
type: Opaque
